### ISSUE TITLE
Unable to create a project with blog template

### ISSUE THREAD

**Issue by JamieBradders** [carrot/roots-template-blog#1]
Hey guys, just been working through the 'Roots Templates' video from the website and I've come across an issue when trying to create a roots project with this template.

I've ran the command from the readme and saved the template as 'blog' I have then tried to create the project like so:

`roots new example --template blog`

And I get the following error:

npm ERR! install Couldn't read dependencies
✘ Error: Invalid name: "[object Object]"
Potentially unhandled rejection [3] Error: Invalid name: "[object Object]"
  at ensureValidName (/usr/local/lib/node_modules/roots/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:322:15)
  at Object.module.exports.fixNameField (/usr/local/lib/node_modules/roots/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:211:5)
  at /usr/local/lib/node_modules/roots/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:30:38
  at Array.forEach (native)
  at normalize (/usr/local/lib/node_modules/roots/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:29:15)
  at final (/usr/local/lib/node_modules/roots/node_modules/npm/node_modules/read-package-json/read-json.js:368:33)
  at then (/usr/local/lib/node_modules/roots/node_modules/npm/node_modules/read-package-json/read-json.js:127:33)
  at /usr/local/lib/node_modules/roots/node_modules/npm/node_modules/read-package-json/read-json.js:267:40
  at evalmachine.<anonymous>:271:14
  at /usr/local/lib/node_modules/roots/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
  at Object.oncomplete (evalmachine.<anonymous>:107:15)

Any ideas?

**Comment by kylemac** [comment]
@jbwebesign i think I know what's causing this issue - let me investigate

**Comment by kylemac** [comment]
@jbwebesign i've committed a correction (https://github.com/carrot/roots-template-blog/commit/f1a59d7919c42586143d90c6f6560d693b388b05) please verify it's working for you

**Comment by JamieBradders** [comment]
Yes this has fixed the issue thank you!

**Comment by kylemac** [comment]
great. sorry it was broken for you - feel free to follow up with any questions you have with roots or the blog-template, as well.

**Comment by JamieBradders** [comment]
Not a problem it got fixed and I learned something so it's win win :) and thanks for the support I certainly will do!
